services:
  - type: web
    name: production-monitoring
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: development

  - type: web
    name: production-monitoring-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
